### ISSUE TITLE
can't stream directly in archive within serialize function

### ISSUE THREAD

**Issue by jvdh1978** [Greedysky/json_archive#1]
When I deliver a namevalue pair to the archive it works fine. However if I stream a value directly: e.g. ar& someObject, then I get a unresolved external symbol error. Also with the examples from the boost library: 
https://www.boost.org/doc/libs/1_79_0/libs/serialization/doc/tutorial.html#arrays

I'm not fluent in c++ myself for now, to suggest a fix...

does not work:
void serialize(Archive& ar, const unsigned int version)
	{
		ar& stops;
	}

works:

void serialize(Archive& ar, const unsigned int version)
	{
		ar& BOOST_SERIALIZATION_NVP(stops);
	}

using msvc

**Comment by Greedysky** [comment]
Yeah, Json data structure must have the key-value, so that you should use `make_nvp` instead of `ar & someObject`.
